### Create new user
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name":"Pradeep Kumar",
    "email":"pradeep.kumar@rsystems.com",
    "password":"Admin$123@",
    "mobile":"8802740070",
    "role_id":3
}


### sign-in
POST http://localhost:8080/api/auth 
Content-Type: application/json

{
    "email":"frontendweb.pk@gmail.com",
    "password":"Admin$123@"
}
