### Create new user
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name":"Pradeep Kumar",
    "email":"pradeep.kumar@rsystems.com",
    "password":"Admin$123@",
    "mobile":"7291893484",
    "role_id":2
}


### sign-in
POST http://localhost:3000/api/auth 
Content-Type: application/json

{
    "email":"frontendweb.pk@gmail.com",
    "password":"Admin$123@"
}
