host: http://localhost:3000/api

### Get roles
GET http://localhost:8080/api/role/all
Content-Type: application/json


### Create new role
POST http://localhost:3000/api/role
Content-Type: application/json

{
    "role_name":"admin",
    "permissions":[
         
    ]
}

### Update role
PUT http://localhost:3000/api/role/1
Content-Type: application/json

{
    "role_name":"user",
    "permissions":[
        "user:read",
        "user:update",
        "profile:create",
        "profile:update",
        "post:create",
        "post:read",
        "message:read"
    ]
}


### Delete role
DELETE  http://localhost:3000/api/role/1
Content-Type: application/json